### ISSUE TITLE
Per-database lock-method settings

### ISSUE THREAD

**Issue by StafDehat** [holland-backup/holland#120]
Currently, if I want to force the single-transaction lock method on one database, but continue using auto-detect (default) on the other databases, I have to create two backupsets:
1) Force single-transaction and include only the target database.
2) Use the default auto-detect lock-method, and backup all database except the target database.

It would be nice if I could continue using only one backupset and specific within the config to force a particular lock-method on a specific database, but use the default on all others.

I guess ultimately I'm asking for both a global and a database-level setting for lock-method (and potentially for any other arguments for which this makes sense).  The global setting would be required (or default to auto-detect), and the database-level setting would override the global.

**Comment by m00dawg** [comment]
This was discussed early on in Holland development as I recall, and the end result is how things are today with multiple backup-sets. Among the reasons were keeping things simpler and static and avoiding inconsistencies that might not be clear. For instance, mixing single-transaction and auto-detect databases into a single backup set could cause confusion about which databases where backed up using what method, which could be really important if you need cross database integrity.

Your current approach would be what I would recommend. Note that if you are not already doing so, you can define sort of 'default' backup sets that Holland will use if you simply run 'holland bk'. You can do so by editing the main holland.conf and adding your preferred backups to the backupsets list (e.g. backupsets = single-trans-dbs, auto-detect-dbs).

All that said, alternatives that would provide a binary backup of MySQL (instead of a logical SQL one) would be to consider LVM, mysqldump + LVM, or xtrabackup. The latter requires you are only using InnoDB tables (TokuDB and other such engines are not supported; MyISAM works but is inconsistent) but is my first recommendation. The LVM methods allow you to grab basically a safe backup of the datadir using LVM's snapshoting capability; or you can do mysqldump backups against an LVM snapshot which would be fully consistent (no need to worry about locking methods).

**Comment by abg** [comment]
I think this is a reasonable request.  I would add that I sometimes would like to tune the overall options on a per-database basis (both for mysqldump and pg_dump), not just the lock method.  I think allowing for some sort of ```[mysqldump:<database>]``` override for some subset of the ```[mysqldump]``` section options would be a useful.  This would include at least ```lock-method``` and ```additional-options``` and maybe even some of the filtering options.

**Comment by m00dawg** [comment]
Hmm you think? That's a departure from how we approached things originally. I actually rather like keeping backup-set configurations rather distinct. Adding something like that might add complexity for something I thought was otherwise pretty straightforward.

Granted, for cases where there's a huge amount of databases, I could see something like this being of some benefit. I do worry it might be bringing a shotgun to a knife party though. If we go this route, should document these additions well, and perhaps add a warning that it's an advanced feature?

Just my $0.02

**Comment by abg** [comment]
Maintaining separate backupsets add a non-trivial burden, IMHO.   I tend to like separate backupsets for separate instances but for a single database where I might want to adjust a single option it's definitely a pain.

I am rarely interested in doing inconsistent mysqldump backups but there are certainly environments where strict consistency is unnecessary and undesirable.   Or binary logging is not enabled so there's not really a point in a perfect instance-wide snapshot (which is not the case anyway here with file-per-database mode enabled).   Or where stop-slave (or --dump-slave) is being used so consistency is roughly guaranteed in other ways but it would be convenient to tweak the individual mysqldump commandline in some way.

Holland logs the options it's using in its output.   The original configuration file is transferred with the backup into the associated backup.conf so you can see what options were used at the time the mysqldump backups were generated.   Again, IMO, it is certainly a lot easier than juggling around multiple backupsets.

I don't think this is terribly complicated to implement either.

**Comment by m00dawg** [comment]
Worried less about the implementation and more over how it's used. I'd want to avoid any assumptions made that doing this results in consistent backups. I think as long as we cover that base it'd be ok, though I still find using backups sets sufficient :) But this does allow for more options for sure.

**Comment by abg** [comment]
You keep using the word consistency.  The only case per database options would make sense if if a separate mysqldump invocation is used per database - i.e. file-per-database is enabled.  That option is currently the holland-mysqldump plugin's default behavior and already disables cross-database consistency.  A user can already disable consistency by setting 'single-transaction' globally which means MyISAM tables can drift.  I don't consider per-database options any worse than the current state.

**Comment by soulen3** [comment]
I believe the use case should be covered by arg_per_database feature added in 057a7a2813b6c80d0fd01dfbddabd1ca01306500
